baseURL = ""
relativeurls = true
languageCode = "en-us"
title = "Mustafa Akın"
disqusShortname = "mustafaakindev"
googleAnalytics = "UA-163369693-1"

[params]
  description = "SRE Architect @Atlassian Opsgenie, PhD Student @Bilkent University CS"
	layoutReverse = false

[Menus]
  main = [
      {Name = "Twitter", URL = "https://twitter.com/mustafaakin/"},
      {Name = "Github", URL = "https://github.com/mustafaakin/"},
      {Name = "LinkedIn", URL = "https://www.linkedin.com/in/mustafaakin/"}
  ]

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNumbersInTable = false
    noClasses = false
    style = "github"
